TEAM_NAME_MAP = {
    "Abilene Christian Wildcats": "Abilene Christian",
    "Air Force Falcons": "Air Force",
    "Akron Zips": "Akron",
    "Alabama Crimson Tide": "Alabama",
    "Alabama A&M Bulldogs": "Alabama A&M",
    "Alabama State Hornets": "Alabama State",
    "Alcorn State Braves": "Alcorn State",
    "American University Eagles": "American University",
    "App State Mountaineers": "App State",
    "Arizona Wildcats": "Arizona",
    "Arizona State Sun Devils": "Arizona State",
    "Arkansas Razorbacks": "Arkansas",
    "Arkansas State Red Wolves": "Arkansas State",
    "Arkansas-Pine Bluff Golden Lions": "Arkansas-Pine Bluff",
    "Army Black Knights": "Army",
    "Auburn Tigers": "Auburn",
    "Austin Peay Governors": "Austin Peay",
    "BYU Cougars": "BYU",
    "Ball State Cardinals": "Ball State",
    "Baylor Bears": "Baylor",
    "Bellarmine Knights": "Bellarmine",
    "Belmont Bruins": "Belmont",
    "Bethune-Cookman Wildcats": "Bethune-Cookman",
    "Binghamton Bearcats": "Binghamton",
    "Boise State Broncos": "Boise State",
    "Boston College Eagles": "Boston College",
    "Boston University Terriers": "Boston University",
    "Bowling Green Falcons": "Bowling Green",
    "Bradley Braves": "Bradley",
    "Brown Bears": "Brown",
    "Bryant Bulldogs": "Bryant",
    "Bucknell Bison": "Bucknell",
    "Buffalo Bulls": "Buffalo",
    "Butler Bulldogs": "Butler",
    "Cal Poly Mustangs": "Cal Poly",
    "Cal State Bakersfield Roadrunners": "Cal State Bakersfield",
    "Cal State Fullerton Titans": "Cal State Fullerton",
    "Cal State Northridge Matadors": "Cal State Northridge",
    "California Golden Bears": "California",
    "California Baptist Lancers": "California Baptist",
    "Campbell Fighting Camels": "Campbell",
    "Canisius Golden Griffins": "Canisius",
    "Central Arkansas Bears": "Central Arkansas",
    "Central Connecticut Blue Devils": "Central Connecticut",
    "Central Michigan Chippewas": "Central Michigan",
    "Charleston Cougars": "Charleston",
    "Charleston Southern Buccaneers": "Charleston Southern",
    "Charlotte 49ers": "Charlotte",
    "Chattanooga Mocs": "Chattanooga",
    "Chicago State Cougars": "Chicago State",
    "Cincinnati Bearcats": "Cincinnati",
    "Clemson Tigers": "Clemson",
    "Cleveland State Vikings": "Cleveland State",
    "Coastal Carolina Chanticleers": "Coastal Carolina",
    "Colgate Raiders": "Colgate",
    "Colorado Buffaloes": "Colorado",
    "Colorado State Rams": "Colorado State",
    "Columbia Lions": "Columbia",
    "Coppin State Eagles": "Coppin State",
    "Cornell Big Red": "Cornell",
    "Creighton Bluejays": "Creighton",
    "Dartmouth Big Green": "Dartmouth",
    "Davidson Wildcats": "Davidson",
    "Dayton Flyers": "Dayton",
    "DePaul Blue Demons": "DePaul",
    "Delaware Blue Hens": "Delaware",
    "Delaware State Hornets": "Delaware State",
    "Denver Pioneers": "Denver",
    "Detroit Mercy Titans": "Detroit Mercy",
    "Drake Bulldogs": "Drake",
    "Drexel Dragons": "Drexel",
    "Duke Blue Devils": "Duke",
    "Duquesne Dukes": "Duquesne",
    "East Carolina Pirates": "East Carolina",
    "East Tennessee State Buccaneers": "East Tennessee State",
    "Eastern Illinois Panthers": "Eastern Illinois",
    "Eastern Kentucky Colonels": "Eastern Kentucky",
    "Eastern Michigan Eagles": "Eastern Michigan",
    "Eastern Washington Eagles": "Eastern Washington",
    "Elon Phoenix": "Elon",
    "Evansville Purple Aces": "Evansville",
    "Fairfield Stags": "Fairfield",
    "Fairleigh Dickinson Knights": "Fairleigh Dickinson",
    "Florida Gators": "Florida",
    "Florida A&M Rattlers": "Florida A&M",
    "Florida Atlantic Owls": "Florida Atlantic",
    "Florida Gulf Coast Eagles": "Florida Gulf Coast",
    "Florida International Panthers": "Florida International",
    "Florida State Seminoles": "Florida State",
    "Fordham Rams": "Fordham",
    "Fresno State Bulldogs": "Fresno State",
    "Furman Paladins": "Furman",
    "Gardner-Webb Runnin' Bulldogs": "Gardner-Webb",
    "George Mason Patriots": "George Mason",
    "George Washington Revolutionaries": "George Washington",
    "Georgetown Hoyas": "Georgetown",
    "Georgia Bulldogs": "Georgia",
    "Georgia Southern Eagles": "Georgia Southern",
    "Georgia State Panthers": "Georgia State",
    "Georgia Tech Yellow Jackets": "Georgia Tech",
    "Gonzaga Bulldogs": "Gonzaga",
    "Grambling Tigers": "Grambling",
    "Grand Canyon Lopes": "Grand Canyon",
    "Green Bay Phoenix": "Green Bay",
    "Hampton Pirates": "Hampton",
    "Harvard Crimson": "Harvard",
    "Hawai'i Rainbow Warriors": "Hawai'i",
    "High Point Panthers": "High Point",
    "Hofstra Pride": "Hofstra",
    "Holy Cross Crusaders": "Holy Cross",
    "Houston Cougars": "Houston",
    "Houston Christian Huskies": "Houston Christian",
    "Howard Bison": "Howard",
    "IU Indianapolis Jaguars": "IU Indianapolis",
    "Idaho Vandals": "Idaho",
    "Idaho State Bengals": "Idaho State",
    "Illinois Fighting Illini": "Illinois",
    "Illinois State Redbirds": "Illinois State",
    "Incarnate Word Cardinals": "Incarnate Word",
    "Indiana Hoosiers": "Indiana",
    "Indiana State Sycamores": "Indiana State",
    "Iona Gaels": "Iona",
    "Iowa Hawkeyes": "Iowa",
    "Iowa State Cyclones": "Iowa State",
    "Jackson State Tigers": "Jackson State",
    "Jacksonville Dolphins": "Jacksonville",
    "Jacksonville State Gamecocks": "Jacksonville State",
    "James Madison Dukes": "James Madison",
    "Kansas Jayhawks": "Kansas",
    "Kansas City Roos": "Kansas City",
    "Kansas State Wildcats": "Kansas State",
    "Kennesaw State Owls": "Kennesaw State",
    "Kent State Golden Flashes": "Kent State",
    "Kentucky Wildcats": "Kentucky",
    "LSU Tigers": "LSU",
    "La Salle Explorers": "La Salle",
    "Lafayette Leopards": "Lafayette",
    "Lamar Cardinals": "Lamar",
    "Le Moyne Dolphins": "Le Moyne",
    "Lehigh Mountain Hawks": "Lehigh",
    "Liberty Flames": "Liberty",
    "Lindenwood Lions": "Lindenwood",
    "Lipscomb Bisons": "Lipscomb",
    "Little Rock Trojans": "Little Rock",
    "Long Beach State Beach": "Long Beach State",
    "Long Island University Sharks": "Long Island University",
    "Longwood Lancers": "Longwood",
    "Louisiana Ragin' Cajuns": "Louisiana",
    "Louisiana Tech Bulldogs": "Louisiana Tech",
    "Louisville Cardinals": "Louisville",
    "Loyola Chicago Ramblers": "Loyola Chicago",
    "Loyola Maryland Greyhounds": "Loyola Maryland",
    "Loyola Marymount Lions": "Loyola Marymount",
    "Maine Black Bears": "Maine",
    "Manhattan Jaspers": "Manhattan",
    "Marist Red Foxes": "Marist",
    "Marquette Golden Eagles": "Marquette",
    "Marshall Thundering Herd": "Marshall",
    "Maryland Terrapins": "Maryland",
    "Maryland Eastern Shore Hawks": "Maryland Eastern Shore",
    "Massachusetts Minutemen": "Massachusetts",
    "McNeese Cowboys": "McNeese",
    "Memphis Tigers": "Memphis",
    "Mercer Bears": "Mercer",
    "Mercyhurst Lakers": "Mercyhurst",
    "Merrimack Warriors": "Merrimack",
    "Miami Hurricanes": "Miami",
    "Miami (OH) RedHawks": "Miami (OH)",
    "Michigan Wolverines": "Michigan",
    "Michigan State Spartans": "Michigan State",
    "Middle Tennessee Blue Raiders": "Middle Tennessee",
    "Milwaukee Panthers": "Milwaukee",
    "Minnesota Golden Gophers": "Minnesota",
    "Mississippi State Bulldogs": "Mississippi State",
    "Mississippi Valley State Delta Devils": "Mississippi Valley State",
    "Missouri Tigers": "Missouri",
    "Missouri State Bears": "Missouri State",
    "Monmouth Hawks": "Monmouth",
    "Montana Grizzlies": "Montana",
    "Montana State Bobcats": "Montana State",
    "Morehead State Eagles": "Morehead State",
    "Morgan State Bears": "Morgan State",
    "Mount St. Mary's Mountaineers": "Mount St. Mary's",
    "Murray State Racers": "Murray State",
    "NC State Wolfpack": "NC State",
    "NJIT Highlanders": "NJIT",
    "Navy Midshipmen": "Navy",
    "Nebraska Cornhuskers": "Nebraska",
    "Nevada Wolf Pack": "Nevada",
    "New Hampshire Wildcats": "New Hampshire",
    'New Haven Chargers' : 'New Haven',
    "New Mexico Lobos": "New Mexico",
    "New Mexico State Aggies": "New Mexico State",
    "New Orleans Privateers": "New Orleans",
    "Niagara Purple Eagles": "Niagara",
    "Nicholls Colonels": "Nicholls",
    "Norfolk State Spartans": "Norfolk State",
    "North Alabama Lions": "North Alabama",
    "North Carolina Tar Heels": "North Carolina",
    "North Carolina A&T Aggies": "North Carolina A&T",
    "North Carolina Central Eagles": "North Carolina Central",
    "North Dakota Fighting Hawks": "North Dakota",
    "North Dakota State Bison": "North Dakota State",
    "North Florida Ospreys": "North Florida",
    "North Texas Mean Green": "North Texas",
    "Northeastern Huskies": "Northeastern",
    "Northern Arizona Lumberjacks": "Northern Arizona",
    "Northern Colorado Bears": "Northern Colorado",
    "Northern Illinois Huskies": "Northern Illinois",
    "Northern Iowa Panthers": "Northern Iowa",
    "Northern Kentucky Norse": "Northern Kentucky",
    "Northwestern Wildcats": "Northwestern",
    "Northwestern State Demons": "Northwestern State",
    "Notre Dame Fighting Irish": "Notre Dame",
    "Oakland Golden Grizzlies": "Oakland",
    "Ohio Bobcats": "Ohio",
    "Ohio State Buckeyes": "Ohio State",
    "Oklahoma Sooners": "Oklahoma",
    "Oklahoma State Cowboys": "Oklahoma State",
    "Old Dominion Monarchs": "Old Dominion",
    "Ole Miss Rebels": "Ole Miss",
    "Omaha Mavericks": "Omaha",
    "Oral Roberts Golden Eagles": "Oral Roberts",
    "Oregon Ducks": "Oregon",
    "Oregon State Beavers": "Oregon State",
    "Pacific Tigers": "Pacific",
    "Penn State Nittany Lions": "Penn State",
    "Pennsylvania Quakers": "Pennsylvania",
    "Pepperdine Waves": "Pepperdine",
    "Pittsburgh Panthers": "Pittsburgh",
    "Portland Pilots": "Portland",
    "Portland State Vikings": "Portland State",
    "Prairie View A&M Panthers": "Prairie View A&M",
    "Presbyterian Blue Hose": "Presbyterian",
    "Princeton Tigers": "Princeton",
    "Providence Friars": "Providence",
    "Purdue Boilermakers": "Purdue",
    "Purdue Fort Wayne Mastodons": "Purdue Fort Wayne",
    "Queens University Royals": "Queens University",
    "Quinnipiac Bobcats": "Quinnipiac",
    "Radford Highlanders": "Radford",
    "Rhode Island Rams": "Rhode Island",
    "Rice Owls": "Rice",
    "Richmond Spiders": "Richmond",
    "Rider Broncs": "Rider",
    "Robert Morris Colonials": "Robert Morris",
    "Rutgers Scarlet Knights": "Rutgers",
    "SE Louisiana Lions": "SE Louisiana",
    "SIU Edwardsville Cougars": "SIU Edwardsville",
    "SMU Mustangs": "SMU",
    "Sacramento State Hornets": "Sacramento State",
    "Sacred Heart Pioneers": "Sacred Heart",
    "Saint Joseph's Hawks": "Saint Joseph's",
    "Saint Louis Billikens": "Saint Louis",
    "Saint Mary's Gaels": "Saint Mary's",
    "Saint Peter's Peacocks": "Saint Peter's",
    "Sam Houston Bearkats": "Sam Houston",
    "Samford Bulldogs": "Samford",
    "San Diego Toreros": "San Diego",
    "San Diego State Aztecs": "San Diego State",
    "San Francisco Dons": "San Francisco",
    "San José State Spartans": "San José State",
    "Santa Clara Broncos": "Santa Clara",
    "Seattle U Redhawks": "Seattle U",
    "Seton Hall Pirates": "Seton Hall",
    "Siena Saints": "Siena",
    "South Alabama Jaguars": "South Alabama",
    "South Carolina Gamecocks": "South Carolina",
    "South Carolina State Bulldogs": "South Carolina State",
    "South Carolina Upstate Spartans": "South Carolina Upstate",
    "South Dakota Coyotes": "South Dakota",
    "South Dakota State Jackrabbits": "South Dakota State",
    "South Florida Bulls": "South Florida",
    "Southeast Missouri State Redhawks": "Southeast Missouri State",
    "Southern Jaguars": "Southern",
    "Southern Illinois Salukis": "Southern Illinois",
    "Southern Indiana Screaming Eagles": "Southern Indiana",
    "Southern Miss Golden Eagles": "Southern Miss",
    "Southern Utah Thunderbirds": "Southern Utah",
    "St. Bonaventure Bonnies": "St. Bonaventure",
    "Saint Francis Red Flash": "St. Francis (PA)",
    "St. John's Red Storm": "St. John's",
    "St. Thomas-Minnesota Tommies": "St. Thomas-Minnesota",
    "Stanford Cardinal": "Stanford",
    "Stephen F. Austin Lumberjacks": "Stephen F. Austin",
    "Stetson Hatters": "Stetson",
    "Stonehill Skyhawks": "Stonehill",
    "Stony Brook Seawolves": "Stony Brook",
    "Syracuse Orange": "Syracuse",
    "TCU Horned Frogs": "TCU",
    "Tarleton State Texans": "Tarleton State",
    "Temple Owls": "Temple",
    "Tennessee Volunteers": "Tennessee",
    "Tennessee State Tigers": "Tennessee State",
    "Tennessee Tech Golden Eagles": "Tennessee Tech",
    "Texas Longhorns": "Texas",
    "Texas A&M Aggies": "Texas A&M",
    "East Texas A&M Lions": "East Texas A&M",
    "Texas A&M-Corpus Christi Islanders": "Texas A&M-Corpus Christi",
    "Texas Southern Tigers": "Texas Southern",
    "Texas State Bobcats": "Texas State",
    "Texas Tech Red Raiders": "Texas Tech",
    "The Citadel Bulldogs": "The Citadel",
    "Toledo Rockets": "Toledo",
    "Towson Tigers": "Towson",
    "Troy Trojans": "Troy",
    "Tulane Green Wave": "Tulane",
    "Tulsa Golden Hurricane": "Tulsa",
    "UAB Blazers": "UAB",
    "UAlbany Great Danes": "UAlbany",
    "UC Davis Aggies": "UC Davis",
    "UC Irvine Anteaters": "UC Irvine",
    "UC Riverside Highlanders": "UC Riverside",
    "UC San Diego Tritons": "UC San Diego",
    "UC Santa Barbara Gauchos": "UC Santa Barbara",
    "UCF Knights": "UCF",
    "UCLA Bruins": "UCLA",
    "UConn Huskies": "UConn",
    "UIC Flames": "UIC",
    "UL Monroe Warhawks": "UL Monroe",
    "UMBC Retrievers": "UMBC",
    "UMass Lowell River Hawks": "UMass Lowell",
    "UNC Asheville Bulldogs": "UNC Asheville",
    "UNC Greensboro Spartans": "UNC Greensboro",
    "UNC Wilmington Seahawks": "UNC Wilmington",
    "UNLV Rebels": "UNLV",
    "USC Trojans": "USC",
    "UT Arlington Mavericks": "UT Arlington",
    "UT Martin Skyhawks": "UT Martin",
    "UT Rio Grande Valley Vaqueros": "UT Rio Grande Valley",
    "UTEP Miners": "UTEP",
    "UTSA Roadrunners": "UTSA",
    "Utah Utes": "Utah",
    "Utah State Aggies": "Utah State",
    "Utah Tech Trailblazers": "Utah Tech",
    "Utah Valley Wolverines": "Utah Valley",
    "VCU Rams": "VCU",
    "VMI Keydets": "VMI",
    "Valparaiso Beacons": "Valparaiso",
    "Vanderbilt Commodores": "Vanderbilt",
    "Vermont Catamounts": "Vermont",
    "Villanova Wildcats": "Villanova",
    "Virginia Cavaliers": "Virginia",
    "Virginia Tech Hokies": "Virginia Tech",
    "Wagner Seahawks": "Wagner",
    "Wake Forest Demon Deacons": "Wake Forest",
    "Washington Huskies": "Washington",
    "Washington State Cougars": "Washington State",
    "Weber State Wildcats": "Weber State",
    "West Georgia Wolves": "West Georgia",
    "West Virginia Mountaineers": "West Virginia",
    "Western Carolina Catamounts": "Western Carolina",
    "Western Illinois Leathernecks": "Western Illinois",
    "Western Kentucky Hilltoppers": "Western Kentucky",
    "Western Michigan Broncos": "Western Michigan",
    "Wichita State Shockers": "Wichita State",
    "William & Mary Tribe": "William & Mary",
    "Winthrop Eagles": "Winthrop",
    "Wisconsin Badgers": "Wisconsin",
    "Wofford Terriers": "Wofford",
    "Wright State Raiders": "Wright State",
    "Wyoming Cowboys": "Wyoming",
    "Xavier Musketeers": "Xavier",
    "Yale Bulldogs": "Yale",
    "Youngstown State Penguins": "Youngstown State",
}

def normalize_team_name(name):
    return TEAM_NAME_MAP.get(name, name)